### ISSUE TITLE
Multiple BLE connections not possible anymore since ESPHome 2022.9.3

### ISSUE THREAD

**Issue by Manu0171discord** [syssi/esphome-jk-bms#189] opened 2022-10-11 10:35 UTC
Hi,
I tried the example yaml file to manage 2 jkbms with 1 esp32
jkbms is compliant as described into the yaml file

https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-example-multiple-devices.yaml

The first jkbms which is kept by the BT connection of the esp32 is the only one
no connection with the second jkbms (different mac address from the 1st one)

In summary, only can have data into HA/esphome for 1 jkbms (bms0 and bms1 values are the same)

NB : if you modify this script for 1 jkbms / 1 esp32 it works but you will have 2 esp32 and not 1 esp32

**Comment by syssi** [comment] 2022-10-11 13:09
Please check your ESPHome version. There was a bug in the past which leads to the described behavior. Please update ESPHome to the latest release + compile & flash the node again.

**Comment by Bandit-17** [comment] 2022-10-11 13:50
Hello Sebastian,
we are using the dev version of esphome with anaconda (version: 2022.10.0-dev)

here is the file we are working on
[teste2bmsble.txt](https://github.com/syssi/esphome-jk-bms/files/9756452/teste2bmsble.txt)

unfortunately we have the values ​​of the 1st BMS which is grafted onto the 2nd (see capture)
![unknown](https://user-images.githubusercontent.com/105204131/195109284-d78551c8-0a15-4a75-930e-885feacd9167.png)

**Comment by Bandit-17** [comment] 2022-10-11 13:55
we try to integrate the BLE part of the JKBMS in the Pvbrain, to recover the information not available with the RS485.

**Comment by syssi** [comment] 2022-10-11 14:01
This is strange. Could you try the IDF framework instead if Arduino?

**Comment by syssi** [comment] 2022-10-11 14:12
Another idea: May be multiple BLE clients are broken (again) at ESPHome 2022.10.0. Please downgrade to `2022.8.3` by:

``` 
pip3 install esphome==2022.8.3
```

And use the ESPHome 2022.8.3 compatible release of this external component:

```
substitutions:
  external_components_source: github://syssi/esphome-jk-bms@1.3.0
```

Are you able to monitor two JK-BMS simultaneously now?

**Comment by Manu0171discord** [comment] 2022-10-11 18:35
We, bandit17 and I tried with your instructions but it does not work neither this way.

**Comment by syssi** [comment] 2022-10-11 19:02
Alright. I'm back home in a few days and will try to reproduce the issue on my testbench.

**Comment by Manu0171discord** [comment] 2022-10-11 20:18
We thank you very much for your time and work you've done
there is no emergency for sure but if you can reproduce the case, it is very nice.

**Comment by syssi** [comment] 2022-10-17 08:17
@proasnet May be this issue is relevant for you too or you are able to verify multiple BLE client connections are still working.

Long story short: @Bandit-17 and @Manu0171discord are trying to talk to 2 BMS using one ESP32. If I remember correctly you are doing the same successfully(?).

**Comment by proasnet** [comment] 2022-10-17 08:28
Yes, right.

**Comment by proasnet** [comment] 2022-10-17 08:30
But, one month before some ESPHome update, both BMS worked via BT on the one ESP32. Now not.

**Comment by syssi** [comment] 2022-10-17 08:36
```
[12:49:57][I][app:102]: ESPHome version 2022.9.1 compiled on Sep 22 2022, 12:47:24
# https://github.com/syssi/esphome-jk-bms/issues/160#issuecomment-1254943112
```

**Comment by proasnet** [comment] 2022-10-17 08:44
Yes, we have addressed this. This seems to be the problem, not in the wifi, but as described in this post
@Bandit-17 and @Manu0171discord are trying to talk to 2 BMS using one ESP32.

**Comment by proasnet** [comment] 2022-10-17 08:45
As I read, is needed downgrade ESPHome?

**Comment by syssi** [comment] 2022-10-17 08:51
Could you try to compare the behavior of the most recent ESPHome version:

```
pip3 install esphome==2022.9.4 -U
```

plus

```
substitutions:
  external_components_source: github://syssi/esphome-jk-bms@main
```

Versus the ESPHome version you did use successfully in the past:

```
pip3 install esphome==2022.9.1 -U
```

```
substitutions:
  external_components_source: github://syssi/esphome-jk-bms@1.3.0
```

Do you see a difference?

**Comment by proasnet** [comment] 2022-10-17 09:03
I am sorry, where I use this command?
In the terminal, not working...
bash: command not found
pip3 install esphome==2022.9.1 -U
I am lama :D

**Comment by syssi** [comment] 2022-10-17 09:30
If you use the Home Assistant Addon are you able to up-/downgrade the ESPHome version? If not I will explain how to install `esphome` manually and use it (for testing) at the terminal.

**Comment by proasnet** [comment] 2022-10-17 11:36
I can not downgrade ESPHome. In addons, I can get only latest version.

**Comment by syssi** [comment] 2022-10-17 11:44
Alright. Do you have access to a linux host? You could try to follow this tutorial:

![Screen recording](https://raw.githubusercontent.com/syssi/esphome-seplos-bms/main/install.gif)

**Comment by proasnet** [comment] 2022-10-17 11:50
You mean another PC with linux? Not now, I am in work with win PC, but at home I have PC with ubuntu

**Comment by proasnet** [comment] 2022-10-17 12:10
I have the option to install ESPHome in docker in the synology server, but then I don't know how to get to his files, I don't understand these Linux things that much.
![Bez názvu](https://user-images.githubusercontent.com/76579362/196173592-f31f1f5e-fb1b-455b-8daa-c8902bfad4e2.png)

**Comment by proasnet** [comment] 2022-10-19 12:41
I am sorry, my ubuntu pc not working. I cant test it for you.
Now I am trying update ESPHome to 2022.10.0 with backup previous.

**Comment by proasnet** [comment] 2022-10-25 07:24
New status:
The second BMS has after some time the same values as the first BMS. The real values of the second BMS is not readed.
The second BMS is not really connected. LED on device flashing.

**Comment by syssi** [comment] 2022-10-25 07:26
You are using the most recent ESPHome release now because you are unable to downgrade to a previous version. Correct?

**Comment by syssi** [comment] 2022-11-06 10:21
It looks like the BLE client component of ESPHome 2022.10.1 is broken. Please be careful: https://github.com/esphome/issues/issues/3729

**Comment by syssi** [comment] 2022-11-06 17:13
I did start my second JK-BMS today. First findings:

The simultaneous communication with multiple devices is working fine:

- ESPHome 2022.8.3 & Custom component version 1.3.0
- ESPHome 2022.9.0 & Custom component version 1.3.0
- ESPHome 2022.9.1 & Custom component version 1.3.0
- ESPHome 2022.9.2 & Custom component version 1.3.0

Broken versions:

- ESPHome 2022.9.3 & Custom component version `main`
- ESPHome 2022.10.1 & Custom component version `main`
- ESPHome 2022.10.2 & Custom component version `main`

**Comment by proasnet** [comment] 2022-11-06 18:46
that's a good find.  Will it be fixed in the new version?  Or is it necessary to downgrade?
Very thanks.

**Comment by syssi** [comment] 2022-11-06 19:05
The root cause is identified and fixed here: https://github.com/esphome/esphome/commit/0e66c899ce57b304a7697bf4859806e78a07325c

It should work (again) as soon ESPHome `dev` gets released in a few days!

**Comment by Softface** [comment] 2022-11-06 21:00
gooood !
ᐧ

**Comment by Fierofiend** [comment] 2022-11-07 01:03
I am still having this issue with 2022.10.2.

**Comment by Fierofiend** [comment] 2022-11-17 01:27
I just updated to 2022.11.0 and it seems to be fixed.  I am running 10.X-W (10.03) and 8.X (8.20G).

**Comment by proasnet** [comment] 2022-11-17 03:31
Hi @Fierofiend , I am updated HA CORE, ESPHOME and jk-bms node today to last versions, but values of both bms is returned as the same from one bms, no change from previous versions. I see log from jk-bms and see the same values from both.
bms0 and bms1 has the same values, but physicaly has not the same values.

**Comment by proasnet** [comment] 2022-11-17 03:32
![obrazek](https://user-images.githubusercontent.com/76579362/202348281-3767f154-b3b6-4b35-a888-581659194f69.png)

**Comment by syssi** [comment] 2022-11-17 05:17
@proasnet On boot-up the ESPHome node reports the used ESPHome version at the log. Could you make sure you are using a 2022.11 build? I don't think so.

**Comment by proasnet** [comment] 2022-11-17 05:22
You think this?
```
INFO Reading configuration /config/esphome/jk_bms.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
INFO Starting log output from jk-bms.local using esphome API
INFO Successfully connected to jk-bms.local
[06:21:39][I][app:102]: ESPHome version 2022.10.2 compiled on Nov  4 2022, 09:16:55
[06:21:39][I][app:104]: Project syssi.esphome-jk-bms version 1.2.0
```

**Comment by syssi** [comment] 2022-11-17 05:31
Yes! This `2022.10.2` indicates you are not using ESPHome 2022.11 and you did not reflash the ESP recently (`Nov  4 2022, 09:16:55`). Please give it another try! :-)

**Comment by proasnet** [comment] 2022-11-17 05:39
Is interesting, that if I update ESPHome, I will see "UPDATE" on each node, I use it, but is not updated new version of ESPHome. Now, I know it :)
So, cleaned build files, installed to node again, and result is:
Working !!! 
Thank you very much !

**Closed** 2022-11-17 06:18 UTC
Labels: bug
